[package]
name = 'mint_one'
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { local = "../../../aptos/aptos-core/aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../../aptos/aptos-core/aptos-move/framework/aptos-token" }

[addresses]
aptos_framework = "0x1"
# source_addr = owner's address
source_addr = "0x0a6f65c5389cb25206b0778b0411728663f1533da8a51f36d5b14db16b18dbc4"
# change it to `mint_nft = "_" when calling `create-resource-account-and-publish-package` from the cli
# mint_nft = "0xb00b2aef1ffae7256e4fdc345903a6102e7107d9b1ed96a451ad6c110347ce78"
mint_nft = "_"